# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='web', max_length=100),
            preserve_default=False,
        ),
    ]
